from dataclasses import dataclass
import numpy as np 
import PT_adjoint


@dataclass
class Acoustic_2D_Grid_model_params:
    """
    Parameters for 2D acoustic model on a Cartesian grid.
    Inputs: 
        h: the spacing of the grid, which is assumed to be the same in the x and z directions
        c : 2D array of velocity values at each (x,z) grid point. Rows correspond to Z and collumns correspond to X
        ABC_sides: list of integers indicating sides for absorbing boundary conditions 
        stacey_ABCs: bool for using Stacey's ABCs
        sponge_ABCs: bool for using sponge ABCs
        sponge_alpha: float for sponge ABC decay rate (Not used if sponge_ABCs = False)
        sponge_pnts: int for number of points in the sponge layer (Not used if sponge_ABCs = False)
    """
    
    h: float
    Nx: int
    Nz: int
    c: np.ndarray
    ABC_sides: list[int]
    stacey_ABCs: bool
    sponge_ABCs: bool
    sponge_alpha: float 
    sponge_pnts: int

    def __post_init__(self):
        self.c = np.ascontiguousarray(self.c)


@dataclass
class Aquisition_params:
    """
    Aquisition Parameters (right now assuming a 2d acoustic model)
    Inputs: 
    Nt: number of time steps
    delta_t: the time stepping increment
    STFS: 2d numpy array of source time functions, shape (Nt, Ns) where each collumn is a 
		source time function for a source at the corresponding index in source_inds 
    rec_inds: list of tuples indicating the indices (z_gird_point, x_grid_points)
        of the receivers for the wavefield
    """

    Nt: int
    delta_t: float
    STFS: np.ndarray
    source_inds: list[tuple]
    rec_inds: list[tuple]

    def __post_init__(self): 
        if self.STFS.shape[0] != self.Nt:
            raise ValueError("Number of rows in STFS should match Nt")
        if self.STFS.shape[1] != len(self.source_inds): 
            raise ValueError("NUmber of collumns in STFS should match number of source indices")
        

@dataclass
class Preprocess_params:
    """
    Parameters for preprocessing seismic/tomographic data.

    This data class encapsulates settings controlling basic signal preprocessing
    operations such as filtering, amplitude normalization, and muting.

    Parameters
    ----------
    filter : str | None
        Type of filter to apply. Supported value is "lowpass". Use None to skip
        filtering. Note: "highpass" and "lowpass" values exist conceptually but are
        currently not implemented and will raise a ValueError during initialization.
    filter_bounds : list[float]
        Frequency bounds for the filter. For a lowpass filter, provide a one-element
        list [f_high] in Hz.
        Ignored if `filter` is None. The class does not enforce bound ordering here,
        so callers should ensure f_low < f_high where applicable.
    normalize : bool
        If True, apply amplitude normalization to the traces (e.g., scale all traces such
        that the maximum amplitude is 1). 
    mute : bool
        If True, apply muting to suppress unwanted parts of the record (e.g.,
        early/late arrivals or ground roll). Muting is not implemented yet and will
        raise a ValueError during initialization.

    Raises
    ------
    ValueError
        - If `filter` is set to a value other than None, "bandpass", "highpass",
          or "lowpass".
        - If `filter` is "highpass" or "bandpass" (these modes are not implemented yet).
        - If `mute` is True (muting is not implemented yet).

    Notes
    -----
    - This class primarily stores user intent for preprocessing; actual signal
      operations are performed using method from the PT_Data.shot_gather class

    Disclaimer
    ----------
    This documentation summary was generated using AI. The source code in this file
    was not generated by AI.
    """

    mute: bool
    filter: str | None
    filter_bounds: list[float]
    normalize: bool

    def __post_init__(self):
        
        # check filter
        if self.filter:
            if self.filter not in ["highpass", "lowpass", "bandpass"]:
                raise ValueError("filter must either be None or one of highpass, lowpass, or bandpass")
            if self.filter in ["highpass", "bandpass"]:
                raise ValueError("highpass and bandpass filtering aren't to implemented yet")

        # check mute
        if self.mute:
            raise ValueError("Muting in not implemented yet")
        

@dataclass
class Adjoint_params:

    adjoint_source: str
    additonal_parmas: list
    
    def __post_init__(self): 
        self.adjoint_func: callable = getattr(PT_adjoint, self.adjoint_source)



        
